spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://insightops-admin.mysql.database.azure.com:3306/insightops_dashboard?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:insightopsadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:Strongpassword@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:3002}

# 외부 MSA 서비스 연동 설정
external:
  normalization-service:
    base-url: ${NORMALIZATION_SERVICE_URL:http://localhost:8001}
  mail-service:
    base-url: ${MAIL_SERVICE_URL:http://localhost:8003}
  data-ingestion-service:
    base-url: ${DATA_INGESTION_SERVICE_URL:http://localhost:8000}
  voicebot-service:
    base-url: ${VOICEBOT_SERVICE_URL:http://localhost:8002}
  admin-service:
    base-url: ${ADMIN_SERVICE_URL:http://localhost:8004}

# Voicebot Service API를 통해 데이터 조회 (더 이상 직접 DB 연결하지 않음)

# 스케줄러 설정 (API 기반으로 변경되면서 비활성화)
scheduler:
  data-aggregation:
    enabled: false
    cron: "0 0 0 * * ?" # 매일 자정 실행

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# AI 인사이트 서비스 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  max-tokens: ${OPENAI_MAX_TOKENS:2000}
  temperature: ${OPENAI_TEMPERATURE:0.7}
  timeout: ${OPENAI_TIMEOUT:30000}

# AI 인사이트 기능 설정
ai-insights:
  enabled: ${AI_INSIGHTS_ENABLED:true}
  cache:
    enabled: ${AI_CACHE_ENABLED:true}
    ttl: ${AI_CACHE_TTL:3600} # 1시간
  rate-limit:
    enabled: ${AI_RATE_LIMIT_ENABLED:true}
    requests-per-minute: ${AI_RATE_LIMIT_RPM:10}
  fallback:
    enabled: ${AI_FALLBACK_ENABLED:true}
    use-statistical-analysis: ${AI_FALLBACK_STATISTICAL:true}

logging:
  level:
    com.insightops.dashboard: DEBUG
    org.springframework.web: DEBUG
    com.insightops.dashboard.service.AIInsightService: INFO
