spring:
  datasource:
    url: jdbc:mysql://insightops-admin.mysql.database.azure.com:3306/insightops_dashboard?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: insightopsadmin
    password: Strongpassword@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:3002}

# 외부 MSA 서비스 연동 설정
external:
  normalization-service:
    base-url: ${NORMALIZATION_SERVICE_URL:http://localhost:8001}
  mail-service:
    base-url: ${MAIL_SERVICE_URL:http://localhost:8003}
  data-ingestion-service:
    base-url: ${DATA_INGESTION_SERVICE_URL:http://localhost:8000}
  voicebot-service:
    base-url: ${VOICEBOT_SERVICE_URL:http://localhost:8002}
  admin-service:
    base-url: ${ADMIN_SERVICE_URL:http://localhost:8004}

# Voicebot DB 직접 연결 설정 (집계 데이터 생성용)
voicebot:
  datasource:
    url: jdbc:mysql://insightops-admin.mysql.database.azure.com:3306/voicebot?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: insightopsadmin
    password: Strongpassword@
    driver-class-name: com.mysql.cj.jdbc.Driver

# 스케줄러 설정
scheduler:
  data-aggregation:
    enabled: true
    cron: "0 0 0 * * ?" # 매일 자정 실행

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.insightops.dashboard: DEBUG
    org.springframework.web: DEBUG
