spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:production}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://insightops-admin.mysql.database.azure.com:3306/insightops_dashboard?useUnicode=true&characterEncoding=utf8&useSSL=true&sslMode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:dashinyo}
    password: ${SPRING_DATASOURCE_PASSWORD:HappyInyo09@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트
    show-sql: false  # 운영환경에서는 false로 설정
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}

# 외부 MSA 서비스 연동 설정
external:
  normalization-service:
    base-url: ${NORMALIZATION_SERVICE_URL:https://insightops-classification-d2acc8afftgmhubt.koreacentral-01.azurewebsites.net}
  mail-service:
    base-url: ${MAIL_SERVICE_URL:https://insightops-mailsend-e4drbwhqhge4bzam.koreacentral-01.azurewebsites.net}
  data-ingestion-service:
    base-url: ${DATA_INGESTION_SERVICE_URL:http://localhost:8000}
  voicebot-service:
    base-url: ${VOICEBOT_SERVICE_URL:https://insightops-voicebot-aud7gfhwc3fsb3h7.koreacentral-01.azurewebsites.net}
  admin-service:
    base-url: ${ADMIN_SERVICE_URL:http://localhost:8004}

# Voicebot Service API를 통해 데이터 조회 (더 이상 직접 DB 연결하지 않음)

# 스케줄러 설정 (API 기반으로 변경되면서 비활성화)
scheduler:
  data-aggregation:
    enabled: false
    cron: "0 0 0 * * ?" # 매일 자정 실행

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.insightops.dashboard: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

---
# Local development profile with H2 database
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

# 로컬 개발환경에서는 외부 서비스 비활성화
external:
  normalization-service:
    base-url: https://insightops-classification-d2acc8afftgmhubt.koreacentral-01.azurewebsites.net
  mail-service:
    base-url: https://insightops-mailsend-e4drbwhqhge4bzam.koreacentral-01.azurewebsites.net
  data-ingestion-service:
    base-url: http://localhost:8000
  voicebot-service:
    base-url: https://insightops-voicebot-aud7gfhwc3fsb3h7.koreacentral-01.azurewebsites.net
  admin-service:
    base-url: http://localhost:8004

logging:
  level:
    root: INFO
    com.insightops.dashboard: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
