spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://insightops-admin.mysql.database.azure.com:3306/insightops_dashboard?useUnicode=true&characterEncoding=utf8&useSSL=true&sslMode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:dashinyo@insightops-admin}
    password: ${SPRING_DATASOURCE_PASSWORD:HappyInyo09@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:3002}

# 외부 MSA 서비스 연동 설정
external:
  normalization-service:
    base-url: ${NORMALIZATION_SERVICE_URL:http://localhost:8001}
  mail-service:
    base-url: ${MAIL_SERVICE_URL:http://localhost:8003}
  data-ingestion-service:
    base-url: ${DATA_INGESTION_SERVICE_URL:http://localhost:8000}
  voicebot-service:
    base-url: ${VOICEBOT_SERVICE_URL:http://localhost:8002}
  admin-service:
    base-url: ${ADMIN_SERVICE_URL:http://localhost:8004}

# Voicebot Service API를 통해 데이터 조회 (더 이상 직접 DB 연결하지 않음)

# 스케줄러 설정 (API 기반으로 변경되면서 비활성화)
scheduler:
  data-aggregation:
    enabled: false
    cron: "0 0 0 * * ?" # 매일 자정 실행

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.insightops.dashboard: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
